### ISSUE TITLE
Amazon @2x

### ISSUE THREAD

**Issue by ecols33** [Material-Design-Iconography/Icon-Submission#2]
![amazon 2x](https://cloud.githubusercontent.com/assets/12535799/7851411/fa01d9c6-04b4-11e5-98e0-5e849b501657.png)

**Comment by danielhickman** [comment]
Could you pull request it, or do you want me to add you as a contributor?

**Comment by ecols33** [comment]
I would pull request it but I don't know how to upload images to GitHub.
(except through issue requests)

**Comment by crutchcorn** [comment]
Do me a favor and check your Hangouts. I've sent you a message and will help you. :)
